### ISSUE TITLE
Is a pre-qualified pool under consideration?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#109]
Would Alaska consider the introduction of a pre-qualified pool of vendors, similar to California? See https://github.com/cdtprocurement/adpq

**Comment by randyhart** [comment]
Alaska is not planning to establish a vendor pool at this time.  We are planning on having some minimum qualification factors that vendors will need to meet in order to bid on future modules.  We intend to keep the proposal process as light as possible for interested vendors - focused on asking vendors to show vs. tell.  We may also incorporate opportunities for the vendor teams that will be doing the work to discuss their approaches with the Alaska team as part of the proposal process.
