### ISSUE TITLE
Will DHSS change to suit software, or vice versa?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#94]
Is Alaska prepared to change current business process to match existing modular solutions or are all modules expected to be configurable to meet Alaska's current business processes and requirements?

**Comment by randyhart** [comment]
We expect any solution to satisfy the needs that drive existing business processes. Ideally the solution would simplify existing business process and meet all needs. Otherwise, we would not go with that proposed solution. We will also likely stay away from solutions that require extensive configuration on top of a black box.
